CREATE PROCEDURE [dbo].[spx_carga_item_oc]
AS
BEGIN 
	declare @TEMPO TABLE 	 
				(codigo varchar(30))

	INSERT INTO @TEMPO
			(codigo)
	SELECT DISTINCT CODIGO FROM AUX_ITEM_ORDEN_COMPRA
	WHERE CODIGO NOT IN (SELECT COD_PRODUCTO FROM PRODUCTO)
	ORDER BY CODIGO

	INSERT INTO ITEM_ORDEN_COMPRA
		   (COD_ORDEN_COMPRA
		   ,ORDEN
		   ,ITEM
		   ,COD_PRODUCTO
		   ,NOM_PRODUCTO
		   ,CANTIDAD
		   ,PRECIO
		   ,COD_ITEM_NOTA_VENTA
		   ,COD_TIPO_TE
		   ,MOTIVO_TE)
	SELECT	AIOC.NUMERO_OC
			,AIOC.NUMERO_ITEM * 10
			,AIOC.NUMERO_ITEM
			,AIOC.CODIGO
			,AIOC.DESCRIPCION
			,AIOC.CANTIDAD
			,AIOC.VALOR_UNIT
			,NULL	--COD_ITEM_NOTA_VENTA CONVERSADO CON IS ES CONFUSO LA RELACION ENTRE NOTA_VENTA
			,NULL	--COD_TIPO_TE NO EXISTE ESTE DATO EN 4D
			,NULL	--MOTIVO_TE NO EXISTE ESTE DATO EN 4D
	FROM AUX_ITEM_ORDEN_COMPRA AIOC , ORDEN_COMPRA OC
	WHERE AIOC.NUMERO_OC < 129992
	AND AIOC.NUMERO_OC = OC.COD_ORDEN_COMPRA
	AND AIOC.CODIGO IS NOT NULL
	AND AIOC.CODIGO NOT IN (SELECT * FROM @TEMPO)
END
go