ALTER PROCEDURE [dbo].[spdw_faprov_pago] (@ve_codigo NUMERIC,
										   @ve_tipo VARCHAR(20))
AS
BEGIN
	IF (@ve_tipo = 'ORDEN_COMPRA')
	BEGIN
		DECLARE @TEMPO TABLE
		(OC_COD_FAPROV			NUMERIC
		,OC_TOTAL_NETO			NUMERIC
		,OC_COD_PAGO_FAPROV		NUMERIC
		,OC_MONTO_ASIGNADO		NUMERIC
		)
		INSERT INTO @TEMPO
			(OC_COD_FAPROV
			,OC_TOTAL_NETO
			,OC_COD_PAGO_FAPROV
			,OC_MONTO_ASIGNADO)
			--PARA LAS OC, TRAE LAS FACTURAS Y PAGOS
			SELECT DISTINCT FA.COD_FAPROV
				,ITFA.MONTO_ASIGNADO MONTO_ASIGNADO_FA
				--solo muestra los pagos en estado impreso
				,case PF.COD_ESTADO_PAGO_FAPROV
					when 2 then PFF.COD_PAGO_FAPROV
					else null
				end COD_PAGO_FAPROV
				--solo muestra los pagos en estado impreso
				,case PF.COD_ESTADO_PAGO_FAPROV
					when 2 then PFF.MONTO_ASIGNADO
					else null
				end MONTO_ASIGNADO_PAGO 
			FROM   ORDEN_COMPRA OC
				,ITEM_FAPROV ITFA
				,FAPROV FA left outer join PAGO_FAPROV_FAPROV PFF on FA.COD_FAPROV = PFF.COD_FAPROV
						   left outer join PAGO_FAPROV PF on PFF.COD_PAGO_FAPROV = PF.COD_PAGO_FAPROV
			WHERE OC.COD_ORDEN_COMPRA = @ve_codigo
				AND ITFA.COD_DOC = OC.COD_ORDEN_COMPRA
				AND FA.COD_FAPROV = ITFA.COD_FAPROV
				AND FA.ORIGEN_FAPROV = @ve_tipo
				AND FA.COD_ESTADO_FAPROV = 2
		SELECT * FROM @TEMPO
	END
	else IF (@ve_tipo = 'PARTICIPACION')
	BEGIN
		DECLARE @TEMPO2 TABLE
		(PA_COD_FAPROV			NUMERIC
		,PA_TOTAL_NETO			NUMERIC
		,PA_COD_PAGO_FAPROV		NUMERIC
		,PA_MONTO_ASIGNADO		NUMERIC
		)
		INSERT INTO @TEMPO2
			(PA_COD_FAPROV
			,PA_TOTAL_NETO
			,PA_COD_PAGO_FAPROV
			,PA_MONTO_ASIGNADO)
			SELECT DISTINCT FA.COD_FAPROV
				,ITFA.MONTO_ASIGNADO MONTO_ASIGNADO_FA
				,PFF.COD_PAGO_FAPROV
				,PFF.MONTO_ASIGNADO MONTO_ASIGNADO_PAGO
			FROM   PARTICIPACION_ORDEN_PAGO POP
				,ORDEN_PAGO OP
				,PARTICIPACION P
				,TIPO_ORDEN_PAGO T
				,ITEM_FAPROV ITFA
				,FAPROV FA left outer join PAGO_FAPROV_FAPROV PFF on FA.COD_FAPROV = PFF.COD_FAPROV
						   left outer join PAGO_FAPROV PF on PFF.COD_PAGO_FAPROV = PF.COD_PAGO_FAPROV AND PF.COD_ESTADO_PAGO_FAPROV = 2
			WHERE P.COD_PARTICIPACION = @ve_codigo
				AND POP.COD_PARTICIPACION = P.COD_PARTICIPACION
				AND POP.COD_ORDEN_PAGO=OP.COD_ORDEN_PAGO
				AND OP.COD_TIPO_ORDEN_PAGO=T.COD_TIPO_ORDEN_PAGO
				AND ITFA.COD_DOC = P.COD_PARTICIPACION
				AND FA.COD_FAPROV = ITFA.COD_FAPROV
				AND FA.ORIGEN_FAPROV = @ve_tipo
				AND FA.COD_ESTADO_FAPROV = 2

		SELECT * FROM @TEMPO2
	END
	ELSE IF (@ve_tipo='FAPROV')
	BEGIN
			--PARA LAS OC Y FACTURAS DE PARTICIPACION, TRAE LOS PAGOS
			SELECT  'PAGO' TIPO
				,pff.COD_PAGO_FAPROV
				,pff.MONTO_ASIGNADO MONTO_ASIGNADO_PAGO
			FROM FAPROV f
				,PAGO_FAPROV_FAPROV pff
				,PAGO_FAPROV pf
			WHERE f.COD_FAPROV = @ve_codigo
			  AND pff.COD_FAPROV = f.COD_FAPROV
			  AND pf.COD_PAGO_FAPROV = pff.COD_PAGO_FAPROV
			  AND PF.COD_ESTADO_PAGO_FAPROV = 2
			union	-- las NC prov
			select 'NC' TIPO
					,n.cod_ncprov
					,nf.monto_asignado
			from   ncprov_faprov nf, faprov f, ncprov n
			where  f.cod_faprov  = @ve_codigo and
					f.cod_faprov = nf.cod_faprov and
					n.cod_ncprov = nf.cod_ncprov AND
					n.cod_estado_ncprov = 2
	END
END

