ALTER  PROCEDURE [dbo].[spi_solicitud_compra](@ve_cod_solicitud_compra numeric)
AS
BEGIN
	declare @TEMPO TABLE    
	   (COD_SOLICITUD_COMPRA		numeric
		,FECHA_IMPRESION		varchar(100)
		,HORA_IMPRESION			varchar(100)
		,FECHA_SOLICITUD_COMPRA	varchar(100)
		,HORA_SOLICITUD_COMPRA	varchar(100)
		,FECHA_SOLICITUD		varchar(100)
		,USUARIO				varchar(100)
		,COD_PRODUCTO			varchar(100)
		,NOM_PRODUCTO			varchar(100)
		,CANTIDAD				numeric(10,2)
		,NOM_ESTADO_SOLICITUD_COMPRA varchar(100)
		,REFERENCIA				varchar(100)
		,NOM_EMPRESA			varchar(100)
		,TOTAL_ENTRADA			numeric
		,ITEM					varchar(100)
		,IT_COD_PRODUCTO		varchar(100)
		,IT_NOM_PRODUCTO		varchar(100)
		,IT_CANTIDAD			numeric(10,2)
		,PRECIO					numeric
		,TOTAL					numeric
		)

	insert into @TEMPO 
	   (COD_SOLICITUD_COMPRA		
		,FECHA_IMPRESION		
		,HORA_IMPRESION			
		,FECHA_SOLICITUD_COMPRA	
		,HORA_SOLICITUD_COMPRA
		,FECHA_SOLICITUD
		,USUARIO
		,COD_PRODUCTO
		,NOM_PRODUCTO
		,CANTIDAD
		,NOM_ESTADO_SOLICITUD_COMPRA	
		,REFERENCIA	
		,NOM_EMPRESA		
		,TOTAL_ENTRADA
		,ITEM					
		,IT_COD_PRODUCTO			
		,IT_NOM_PRODUCTO			
		,IT_CANTIDAD				
		,PRECIO					
		,TOTAL					
		)
		SELECT SC.COD_SOLICITUD_COMPRA
			,CONVERT(varchar, getdate(), 103) FECHA_IMPRESION
			,CONVERT(varchar, getdate(), 108) HORA_IMPRESION
			,dbo.f_format_date(SC.FECHA_SOLICITUD_COMPRA, 3) FECHA_SOLICITUD_COMPRA
			,CONVERT(varchar, SC.FECHA_SOLICITUD_COMPRA, 108) HORA_SOLICITUD_COMPRA
			,CONVERT(varchar, SC.FECHA_SOLICITUD_COMPRA, 103) FECHA_SOLICITUD
			,U.NOM_USUARIO
			,SC.COD_PRODUCTO
			,PG.NOM_PRODUCTO
			,SC.CANTIDAD
			,ESC.NOM_ESTADO_SOLICITUD_COMPRA
			,SC.REFERENCIA
			,E.NOM_EMPRESA
			,null TOTAL_ENTRADA
			,I.COD_ITEM_SOLICITUD_COMPRA 
			,I.COD_PRODUCTO 
			,P.NOM_PRODUCTO 
			,I.CANTIDAD_TOTAL
			,I.PRECIO_COMPRA
			,round(SC.CANTIDAD * I.PRECIO_COMPRA, 0)	--TOTAL
		FROM SOLICITUD_COMPRA SC
			,USUARIO U
			,PRODUCTO P
			,PRODUCTO PG
			,ESTADO_SOLICITUD_COMPRA ESC
			,ITEM_SOLICITUD_COMPRA I
			,EMPRESA E
		WHERE SC.COD_SOLICITUD_COMPRA = @ve_cod_solicitud_compra
			AND	SC.COD_ESTADO_SOLICITUD_COMPRA = ESC.COD_ESTADO_SOLICITUD_COMPRA
			AND U.COD_USUARIO = SC.COD_USUARIO
			AND P.COD_PRODUCTO = I.COD_PRODUCTO
			AND I.COD_SOLICITUD_COMPRA = SC.COD_SOLICITUD_COMPRA
			AND E.COD_EMPRESA = I.COD_EMPRESA
			AND PG.COD_PRODUCTO = SC.COD_PRODUCTO

	declare
		@vl_suma			numeric

	select @vl_suma = sum(TOTAL)
	from @TEMPO

	update @TEMPO
	set TOTAL_ENTRADA = @vl_suma

	select * from @TEMPO
END