ALTER PROCEDURE [dbo].[spi_tdnx_inv_valor_resumen](@ve_cod_bodega				NUMERIC
													,@ve_fecha					DATETIME)
AS
BEGIN
	DECLARE @TEMP_VALOR_RESUMEN TABLE
				(MODELO							VARCHAR(100)
				,EQUIPO							VARCHAR(100)
				,COD_CLASIF_INVENTARIO			NUMERIC
				,NOM_CORTO_CLASIF_INVENTARIO	VARCHAR(100)
				,NOM_CLASIF_INVENTARIO			VARCHAR(100)
				,STOCK							NUMERIC
				,C_UNIT							NUMERIC
				,COSTO_TOTAL					NUMERIC
				,FECHA							DATETIME )
				
		INSERT INTO @TEMP_VALOR_RESUMEN
						(MODELO
						,EQUIPO
						,COD_CLASIF_INVENTARIO
						,NOM_CORTO_CLASIF_INVENTARIO
						,NOM_CLASIF_INVENTARIO
						,STOCK
						,C_UNIT
						,FECHA)
				SELECT	P.COD_PRODUCTO
						,P.NOM_PRODUCTO
						,P.COD_CLASIF_INVENTARIO
						,C.NOM_CORTO_CLASIF_INVENTARIO
						,C.NOM_CLASIF_INVENTARIO
						,DBO.F_BODEGA_STOCK(P.COD_PRODUCTO,@ve_cod_bodega,@ve_fecha) STOCK
						,DBO.F_BODEGA_PMP(P.COD_PRODUCTO, @ve_cod_bodega, @ve_fecha) C_UNIT
						,@ve_fecha
				FROM	PRODUCTO P, CLASIF_INVENTARIO C
				WHERE	SUBSTRING(SISTEMA_VALIDO, 4, 1) = 'S'
				--AND		P.MANEJA_INVENTARIO = 'S'
				AND		C.COD_CLASIF_INVENTARIO = P.COD_CLASIF_INVENTARIO
				
			UPDATE @TEMP_VALOR_RESUMEN
			SET COSTO_TOTAL = case 
								when STOCK  <= 0 then 0
								else STOCK * C_UNIT
							  end


		SELECT	NOM_CORTO_CLASIF_INVENTARIO
				,NOM_CLASIF_INVENTARIO
				,SUM(COSTO_TOTAL) COSTO_TOTAL
				,CONVERT(VARCHAR(10),FECHA,103) FECHA
		FROM	@TEMP_VALOR_RESUMEN
		GROUP BY NOM_CORTO_CLASIF_INVENTARIO, NOM_CLASIF_INVENTARIO , FECHA
END
