CREATE PROCEDURE [dbo].[spdw_ventana_item_etiqueta](@ve_cod_orden_despacho	NUMERIC)
AS
BEGIN
	DECLARE @TEMP_PRINT_ETIQUETA TABLE
			  (COD_ITEM_ORDEN_DESPACHO	NUMERIC
			  ,COD_ORDEN_DESPACHO		NUMERIC
			  ,COD_PRODUCTO_S			VARCHAR(50)
			  ,COD_PRODUCTO				VARCHAR(50)
			  ,NOM_PRODUCTO				VARCHAR(100)
			  ,CANTIDAD					NUMERIC
			  ,IMPRESION_NORMAL			VARCHAR(1)
			  ,OMITIR_IMPRESION			VARCHAR(1)
			  ,NORMAL_CHECK				VARCHAR(1)
			  ,BULTO_UNO				NUMERIC
			  ,BULTO_DOS				NUMERIC
			  ,BULTO_TRES				NUMERIC
			  ,BULTO_CUATRO				NUMERIC
			  ,BULTO_CINCO				NUMERIC
			  ,BULTO_SEIS				NUMERIC
			  ,ORDEN					numeric
			  )
	
	--producto de la OD
	insert into @TEMP_PRINT_ETIQUETA
	SELECT COD_ITEM_ORDEN_DESPACHO
		  ,COD_ORDEN_DESPACHO
		  ,COD_PRODUCTO COD_PRODUCTO_S
		  ,COD_PRODUCTO
		  ,NOM_PRODUCTO
		  ,CANTIDAD
		  ,'S' IMPRESION_NORMAL
		  ,'N' OMITIR_IMPRESION
		  ,'S' NORMAL_CHECK
		  ,0 BULTO_UNO
		  ,0 BULTO_DOS
		  ,0 BULTO_TRES
		  ,0 BULTO_CUATRO
		  ,0 BULTO_CINCO
		  ,0 BULTO_SEIS
		  ,ORDEN * 10 
	FROM ITEM_ORDEN_DESPACHO
	WHERE COD_ORDEN_DESPACHO = @ve_cod_orden_despacho
	
	--producto compuestop HIJOS
	insert into @TEMP_PRINT_ETIQUETA
	SELECT i.COD_ITEM_ORDEN_DESPACHO
		  ,i.COD_ORDEN_DESPACHO
		  ,'>&nbsp;&nbsp;&nbsp;' + p.COD_PRODUCTO COD_PRODUCTO_S
		  ,i.COD_PRODUCTO + ' C/PP ' + p.COD_PRODUCTO COD_PRODUCTO
		  ,p.NOM_PRODUCTO
		  ,i.CANTIDAD * pc.CANTIDAD CANTIDAD
		  ,'S' IMPRESION_NORMAL
		  ,'N' OMITIR_IMPRESION
		  ,'S' NORMAL_CHECK
		  ,0 BULTO_UNO
		  ,0 BULTO_DOS
		  ,0 BULTO_TRES
		  ,0 BULTO_CUATRO
		  ,0 BULTO_CINCO
		  ,0 BULTO_SEIS
		  ,i.ORDEN * 10 +1
	FROM ITEM_ORDEN_DESPACHO i, PRODUCTO_COMPUESTO pc, PRODUCTO p
	WHERE i.COD_ORDEN_DESPACHO = @ve_cod_orden_despacho
	and pc.COD_PRODUCTO = i.COD_PRODUCTO
	and p.COD_PRODUCTO = pc.COD_PRODUCTO_HIJO

	select * from @TEMP_PRINT_ETIQUETA
	order by orden
END