set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[spdw_faprov_pagos] (@ve_codigo NUMERIC,
										   @ve_tipo VARCHAR(20))
AS
BEGIN
	IF (@ve_tipo = 'ORDEN_COMPRA')
	BEGIN
		DECLARE @TEMPO TABLE
		(OC_COD_FAPROV			NUMERIC
		,OC_TOTAL_NETO			NUMERIC
		,OC_COD_PAGO_FAPROV		NUMERIC
		,OC_MONTO_ASIGNADO		NUMERIC
		)
		INSERT INTO @TEMPO
			(OC_COD_FAPROV
			,OC_TOTAL_NETO
			,OC_COD_PAGO_FAPROV
			,OC_MONTO_ASIGNADO)
			--PARA LAS OC, TRAE LAS FACTURAS
			SELECT DISTINCT FA.COD_FAPROV
				,ITFA.MONTO_ASIGNADO MONTO_ASIGNADO_FA
				--solo muestra los pagos en estado impreso
				,case PF.COD_ESTADO_PAGO_FAPROV
					when 2 then PFF.COD_PAGO_FAPROV
					else null
				end COD_PAGO_FAPROV
				--solo muestra los pagos en estado impreso
				,case PF.COD_ESTADO_PAGO_FAPROV
					when 2 then PFF.MONTO_ASIGNADO
					else null
				end MONTO_ASIGNADO_PAGO 
			FROM   ORDEN_COMPRA OC
				,ITEM_FAPROV ITFA
				,FAPROV FA left outer join PAGO_FAPROV_FAPROV PFF on FA.COD_FAPROV = PFF.COD_FAPROV
						   left outer join PAGO_FAPROV PF on PFF.COD_PAGO_FAPROV = PF.COD_PAGO_FAPROV
			WHERE OC.COD_ORDEN_COMPRA = @ve_codigo
				AND ITFA.COD_DOC = OC.COD_ORDEN_COMPRA
				AND FA.COD_FAPROV = ITFA.COD_FAPROV
				AND FA.ORIGEN_FAPROV = @ve_tipo
				AND FA.COD_ESTADO_FAPROV = 2
		SELECT * FROM @TEMPO
	END
	ELSE IF (@ve_tipo='FAPROV')
	BEGIN
			--PARA LAS OC Y FACTURAS DE PARTICIPACION, TRAE LOS PAGOS
			SELECT  pff.COD_PAGO_FAPROV
				,pff.MONTO_ASIGNADO MONTO_ASIGNADO_PAGO
			FROM FAPROV f
				,PAGO_FAPROV_FAPROV pff
				,PAGO_FAPROV pf
			WHERE f.COD_FAPROV = @ve_codigo
			  AND pff.COD_FAPROV = f.COD_FAPROV
			  AND pf.COD_PAGO_FAPROV = pff.COD_PAGO_FAPROV
			  AND PF.COD_ESTADO_PAGO_FAPROV = 2
	END
END
go