CREATE PROCEDURE dbo.sp_regula_compromisos_aut_todoinox
AS
BEGIN
	declare @TEMPO TABLE    
	   (COD_BITACORA_FACTURA		NUMERIC)
	
	-- FACTURA (HOY)
	INSERT INTO @TEMPO
	SELECT	BF.COD_BITACORA_FACTURA
	FROM BITACORA_FACTURA BF left outer join USUARIO U2 on U2.COD_USUARIO = BF.COD_USUARIO_REALIZADO, USUARIO U1, FACTURA F, EMPRESA E
	WHERE BF.COD_FACTURA = F.COD_FACTURA
	AND E.COD_EMPRESA = F.COD_EMPRESA
	AND BF.COD_USUARIO = U1.COD_USUARIO
	AND	BF.TIENE_COMPROMISO = 'S'
	AND	(BF.COMPROMISO_REALIZADO =  'N' or BF.COMPROMISO_REALIZADO is null)
	AND BF.FECHA_COMPROMISO <= DATEADD(SECOND,86400 - 1, DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	AND BF.FECHA_COMPROMISO >= DATEADD(SECOND,0 , DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	AND dbo.f_fa_saldo(F.COD_FACTURA) = 0
	   
	-- FACTURA (AYER)
	INSERT INTO @TEMPO
	SELECT	BF.COD_BITACORA_FACTURA
	FROM BITACORA_FACTURA BF left outer join USUARIO U2 on U2.COD_USUARIO = BF.COD_USUARIO_REALIZADO, USUARIO U1, FACTURA F, EMPRESA E
	WHERE BF.COD_FACTURA = F.COD_FACTURA
	AND E.COD_EMPRESA = F.COD_EMPRESA
	AND BF.COD_USUARIO = U1.COD_USUARIO
	AND	BF.TIENE_COMPROMISO = 'S'
	AND	(BF.COMPROMISO_REALIZADO =  'N' or BF.COMPROMISO_REALIZADO is null)
	AND	BF.FECHA_COMPROMISO < DATEADD(SECOND,0 , DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	AND dbo.f_fa_saldo(F.COD_FACTURA) = 0
	
	-- FACTURA (MAÑANA)
	INSERT INTO @TEMPO
	SELECT	BF.COD_BITACORA_FACTURA
	FROM BITACORA_FACTURA BF left outer join USUARIO U2 on U2.COD_USUARIO = BF.COD_USUARIO_REALIZADO, USUARIO U1, FACTURA F, EMPRESA E
	WHERE BF.COD_FACTURA = F.COD_FACTURA
	AND E.COD_EMPRESA = F.COD_EMPRESA
	AND BF.COD_USUARIO = U1.COD_USUARIO
	AND	BF.TIENE_COMPROMISO = 'S'
	AND	(BF.COMPROMISO_REALIZADO =  'N' or BF.COMPROMISO_REALIZADO is null)
	AND	BF.FECHA_COMPROMISO > DATEADD(SECOND,86400 - 1, DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	AND dbo.f_fa_saldo(F.COD_FACTURA) = 0
	
	UPDATE BITACORA_FACTURA
	SET COMPROMISO_REALIZADO = 'S'
	   ,REALIZA_COMPROMISO_AUT = 'S'
	WHERE COD_BITACORA_FACTURA in (SELECT COD_BITACORA_FACTURA FROM @TEMPO)
END