CREATE PROCEDURE dbo.spi_tiene_factura_vendedor_todoinox
AS
BEGIN
	declare @TEMPO TABLE    
	   (COD_USUARIO			NUMERIC)
	
	-- FACTURA (HOY)
	INSERT INTO @TEMPO
	SELECT F.COD_USUARIO_VENDEDOR1
	FROM BITACORA_FACTURA BF left outer join USUARIO U2 on U2.COD_USUARIO = BF.COD_USUARIO_REALIZADO, USUARIO U1, FACTURA F, EMPRESA E
	WHERE BF.COD_FACTURA = F.COD_FACTURA
	AND E.COD_EMPRESA = F.COD_EMPRESA
	AND BF.COD_USUARIO = U1.COD_USUARIO
	AND	BF.TIENE_COMPROMISO = 'S'
	AND	(BF.COMPROMISO_REALIZADO =  'N' or BF.COMPROMISO_REALIZADO is null)
	AND BF.FECHA_COMPROMISO <= DATEADD(SECOND,86400 - 1, DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	AND BF.FECHA_COMPROMISO >= DATEADD(SECOND,0 , DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	   
	-- FACTURA (AYER)
	INSERT INTO @TEMPO
	SELECT F.COD_USUARIO_VENDEDOR1
	FROM BITACORA_FACTURA BF left outer join USUARIO U2 on U2.COD_USUARIO = BF.COD_USUARIO_REALIZADO, USUARIO U1, FACTURA F, EMPRESA E
	WHERE BF.COD_FACTURA = F.COD_FACTURA
	AND E.COD_EMPRESA = F.COD_EMPRESA
	AND BF.COD_USUARIO = U1.COD_USUARIO
	AND	BF.TIENE_COMPROMISO = 'S'
	AND	(BF.COMPROMISO_REALIZADO =  'N' or BF.COMPROMISO_REALIZADO is null)
	AND	BF.FECHA_COMPROMISO < DATEADD(SECOND,0 , DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	
	-- FACTURA (MAÑANA)
	INSERT INTO @TEMPO
	SELECT F.COD_USUARIO_VENDEDOR1
	FROM BITACORA_FACTURA BF left outer join USUARIO U2 on U2.COD_USUARIO = BF.COD_USUARIO_REALIZADO, USUARIO U1, FACTURA F, EMPRESA E
	WHERE BF.COD_FACTURA = F.COD_FACTURA
	AND E.COD_EMPRESA = F.COD_EMPRESA
	AND BF.COD_USUARIO = U1.COD_USUARIO
	AND	BF.TIENE_COMPROMISO = 'S'
	AND	(BF.COMPROMISO_REALIZADO =  'N' or BF.COMPROMISO_REALIZADO is null)
	AND	BF.FECHA_COMPROMISO > DATEADD(SECOND,86400 - 1, DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
	
	SELECT DISTINCT COD_USUARIO FROM @TEMPO
END