-----------------spr_nv_por_fact_por_desp------------------------
CREATE PROCEDURE [dbo].[spr_nv_por_fact_por_desp](@ve_cod_nota_venta numeric, @ve_formato varchar(20))
AS
BEGIN
	DECLARE @TEMPO TABLE
			(COD_NOTA_VENTA		NUMERIC NOT NULL,
			FECHA_NOTA_VENTA	VARCHAR(50) NOT NULL,
			OBS_DESPACHO		TEXT NULL,
			REFERENCIA			VARCHAR(100)NOT NULL,
			NRO_ORDEN_COMPRA	VARCHAR(20)NULL,
			COD_COTIZACION		NUMERIC NULL,
			FECHA_ENTREGA		VARCHAR(50)NULL,
			ATRASO				VARCHAR(50)NULL,
			NOM_USUARIO			VARCHAR(100)NOT NULL,
			NOM_PERSONA			VARCHAR(100)NOT NULL,
			NOM_EMPRESA			VARCHAR(100),
			RUT					NUMERIC NOT NULL,
			DIG_VERIF			VARCHAR(1)NOT NULL,
			DIR_FACTURA			VARCHAR(200)NOT NULL,
			TELEFONO_F			VARCHAR(100)NULL,
			FAX_F				VARCHAR(100)NULL,
			DIR_DESPACHO		VARCHAR(200)NOT NULL,
			TELEFONO_D			VARCHAR(100)NULL,
			FAX_D				VARCHAR(100)NULL,
			ORDENES_COMPRA		VARCHAR(100)NULL,
			ITEM				VARCHAR(10)NULL,
			COD_PRODUCTO		VARCHAR(30) NULL,
			NOM_PRODUCTO		VARCHAR(100)NULL,
			CANTIDAD			NUMERIC(10,2) NOT NULL,
			CANT_FACTURADA		NUMERIC(10,2) NULL,
			CANT_POR_FACTURAR	NUMERIC(10,2) NULL,
			CANT_DESPACHADA		NUMERIC(10,2) NULL,
			CANT_POR_DESPACHAR	NUMERIC(10,2) NULL,
			NOM_EMPRESA_EMISOR	VARCHAR(100)NOT NULL,
			DIR_EMPRESA			VARCHAR(100) NOT NULL,
			TEL_EMPRESA			VARCHAR(100) NOT NULL,
			FAX_EMPRESA			VARCHAR(100) NOT NULL,
			MAIL_EMPRESA		VARCHAR(100) NOT NULL,
			CIUDAD_EMPRESA		VARCHAR(100) NOT NULL,
			PAIS_EMPRESA		VARCHAR(100) NOT NULL,
			SITIO_WEB_EMPRESA	VARCHAR(100)NULL,
			RUT_EMPRESA			VARCHAR(100)NOT NULL)

		
	insert into @TEMPO
	SELECT NV.COD_NOTA_VENTA,
			dbo.f_format_date(NV.FECHA_NOTA_VENTA,3)FECHA_NOTA_VENTA,
			NV.OBS_DESPACHO,
			NV.REFERENCIA,
			NV.NRO_ORDEN_COMPRA,
			NV.COD_COTIZACION,
			dbo.f_format_date(NV.FECHA_ENTREGA, 1)FECHA_ENTREGA,
			DATEDIFF ( day , NV.FECHA_ENTREGA , getdate()) ATRASO,
			U.NOM_USUARIO,
			P.NOM_PERSONA,
			E.NOM_EMPRESA,
			E.RUT,
			E.DIG_VERIF,
			dbo.f_get_direccion('SUCURSAL', NV.COD_SUCURSAL_FACTURA, '[DIRECCION]  [NOM_COMUNA] [NOM_CIUDAD]') DIR_FACTURA,
			SF.TELEFONO TELEFONO_F,
			SF.FAX FAX_F,
			dbo.f_get_direccion('SUCURSAL', NV.COD_SUCURSAL_DESPACHO, '[DIRECCION]  [NOM_COMUNA] [NOM_CIUDAD]') DIR_DESPACHO,
			SD.TELEFONO TELEFONO_D,
			SD.FAX FAX_D,
			dbo.f_nv_oc_por_item(inv.cod_item_nota_venta)ORDENES_COMPRA,
			INV.ITEM,
			INV.COD_PRODUCTO,
			INV.NOM_PRODUCTO,
			INV.CANTIDAD,
			INV.CANTIDAD - dbo.f_nv_cant_por_facturar(inv.cod_item_nota_venta, default) CANT_FACTURADA,
			dbo.f_nv_cant_por_facturar(inv.cod_item_nota_venta,default)CANT_POR_FACTURAR,
			INV.CANTIDAD - dbo.f_nv_cant_por_despachar(inv.cod_item_nota_venta, default) CANT_DESPACHADA,
			dbo.f_nv_cant_por_despachar(inv.cod_item_nota_venta, default)CANT_POR_DESPACHAR,
			dbo.f_get_parametro(6) NOM_EMPRESA_EMISOR,
			dbo.f_get_parametro(10) DIR_EMPRESA,
			dbo.f_get_parametro(11) TEL_EMPRESA,
			dbo.f_get_parametro(12) FAX_EMPRESA,
			dbo.f_get_parametro(13) MAIL_EMPRESA,
			dbo.f_get_parametro(14) CIUDAD_EMPRESA,
			dbo.f_get_parametro(15) PAIS_EMPRESA,
			dbo.f_get_parametro(25) SITIO_WEB_EMPRESA,
			dbo.f_get_parametro(20) RUT_EMPRESA 
	FROM NOTA_VENTA NV, EMPRESA E, SUCURSAL SF,SUCURSAL SD, ITEM_NOTA_VENTA INV,
			PERSONA P, USUARIO U
	WHERE NV.COD_NOTA_VENTA = @ve_cod_nota_venta AND
			E.COD_EMPRESA = NV.COD_EMPRESA AND
			SF.COD_SUCURSAL = NV.COD_SUCURSAL_FACTURA AND
			SD.COD_SUCURSAL = NV.COD_SUCURSAL_DESPACHO AND	
			INV.COD_NOTA_VENTA = NV.COD_NOTA_VENTA AND
			P.COD_PERSONA = NV.COD_PERSONA AND
			U.COD_USUARIO = NV.COD_USUARIO
			
		
	if(@ve_formato = 'POR_FACTURAR')	
		SELECT COD_NOTA_VENTA,
				FECHA_NOTA_VENTA,
				NOM_EMPRESA,  
				RUT,
				DIG_VERIF,
				DIR_FACTURA,
				TELEFONO_F,
				FAX_F,
				REFERENCIA,
				NRO_ORDEN_COMPRA,
				COD_COTIZACION,
				NOM_USUARIO,
				NOM_PERSONA,
				ORDENES_COMPRA,
				ITEM,
				COD_PRODUCTO,
				NOM_PRODUCTO,
				CANTIDAD,
				--CANT_FACTURADA,
				CANT_POR_FACTURAR,
				NOM_EMPRESA_EMISOR,
				DIR_EMPRESA,
				TEL_EMPRESA,
				FAX_EMPRESA,
				MAIL_EMPRESA,
				CIUDAD_EMPRESA,
				PAIS_EMPRESA,
				SITIO_WEB_EMPRESA,
				RUT_EMPRESA 
		   FROM @TEMPO
			where CANT_POR_FACTURAR > 0
	
	else if (@ve_formato = 'POR_DESPACHAR')	
		SELECT COD_NOTA_VENTA,
				FECHA_NOTA_VENTA,
				OBS_DESPACHO,
				NOM_EMPRESA,
				RUT,
				DIG_VERIF,
				DIR_DESPACHO,
				TELEFONO_D,
				FAX_D,
				REFERENCIA,
				NRO_ORDEN_COMPRA,
				COD_COTIZACION,
				FECHA_ENTREGA,
				ATRASO,
				NOM_USUARIO,
				NOM_PERSONA,
				ORDENES_COMPRA,
				ITEM,
				COD_PRODUCTO,
				NOM_PRODUCTO,
				CANTIDAD,
				--CANT_DESPACHADA,
				CANT_POR_DESPACHAR,
				NOM_EMPRESA_EMISOR,
				DIR_EMPRESA,
				TEL_EMPRESA,
				FAX_EMPRESA,
				MAIL_EMPRESA,
				CIUDAD_EMPRESA,
				PAIS_EMPRESA,
				SITIO_WEB_EMPRESA,
				RUT_EMPRESA 
		   FROM @TEMPO
			where CANT_POR_DESPACHAR > 0
END
go

