set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[spr_facturas_por_cliente](@ve_rut_empresa numeric, @ve_fecha_inicio datetime, @ve_fecha_termino datetime)
AS
BEGIN-- declara tabla temporal
	declare @TEMPO TABLE 	 
		   	(NRO_FACTURA			NUMERIC
			,RUT_EMPRESA			NUMERIC
			,REFERENCIA				VARCHAR(100)
			,NRO_ORDEN_COMPRA		VARCHAR(20)
			,NOM_EMPRESA            VARCHAR(100)
			,FECHA_FACTURA			DATETIME
			,TOTAL_NETO				NUMERIC(14,2))
	
-- declara variables
	declare  @NRO_FACTURA			NUMERIC
			,@RUT_EMPRESA			NUMERIC
			,@REFERENCIA			VARCHAR(100)
			,@NRO_ORDEN_COMPRA		VARCHAR(20)
			,@NOM_EMPRESA			VARCHAR(100)
			,@FECHA_FACTURA			DATETIME
			,@TOTAL_NETO			NUMERIC(14,2)

	INSERT INTO @TEMPO
		SELECT	F.NRO_FACTURA
				,E.RUT
				,F.REFERENCIA
				,F.NRO_ORDEN_COMPRA
				,F.NOM_EMPRESA
				,F.FECHA_FACTURA
				,F.TOTAL_NETO
		FROM	EMPRESA E, FACTURA F
		WHERE	E.rut = @ve_rut_empresa
		AND		F.COD_EMPRESA = E.COD_EMPRESA
		AND		F.FECHA_FACTURA BETWEEN @ve_fecha_inicio AND @ve_fecha_termino
		AND		F.COD_ESTADO_DOC_SII in (2,3)
		ORDER BY NRO_FACTURA DESC

		SELECT NRO_FACTURA
				,RUT_EMPRESA
				,REFERENCIA
				,NRO_ORDEN_COMPRA
				,NOM_EMPRESA
				,CONVERT(VARCHAR(10),FECHA_FACTURA,103) FECHA_FACTURA 
				,TOTAL_NETO
		FROM @TEMPO 
		ORDER BY NRO_FACTURA ASC
END
