ALTER function f_oc_GF_por_autorizar()
RETURNS VARCHAR(1)
AS
BEGIN
	DECLARE @VL_COUNT NUMERIC,
			@VL_SI_NO VARCHAR(1),
			@VL_AUTORIZA_MENU VARCHAR(1)
			
		
	
		SELECT @VL_COUNT = COUNT(*)
		FROM ORDEN_COMPRA
		WHERE COD_ESTADO_ORDEN_COMPRA = 1
		  and TIPO_ORDEN_COMPRA = 'GASTO_FIJO'					
		
		IF(@VL_COUNT = 0)
			SET @VL_SI_NO = 'N'
		ELSE 
			SET @VL_SI_NO = 'S'

		
	RETURN @VL_SI_NO
END